import { CodeComponentMeta } from "@plasmicapp/host";
import { DialogProps } from "@radix-ui/react-dialog";
import * as React from "react";
import { ReactElement, ReactNode } from "react";
export declare const enterAnims: readonly ["fade-in", "zoom-enter", "slide-in-from-top", "slide-in-from-right", "slide-in-from-bottom", "slide-in-from-left"];
export type EnterAnim = (typeof enterAnims)[number];
export declare const exitAnims: readonly ["fade-out", "zoom-exit", "slide-out-to-top", "slide-out-to-right", "slide-out-to-bottom", "slide-out-to-left"];
export type ExitAnim = (typeof exitAnims)[number];
export type AnimName = EnterAnim | ExitAnim;
export declare const useId: any;
/** Allow attaching pseudoclasses and other CSS selectors to this unique component instance */
export declare const StyleWrapper: ({ children, cssStr, }: {
    children: (dynClass: string | undefined) => ReactElement;
    cssStr: string;
}) => React.JSX.Element;
export type AnimatedProps = {
    enterAnimations?: EnterAnim[];
    exitAnimations?: ExitAnim[];
    enterDuration?: number;
    exitDuration?: number;
    enterOpacity?: number;
    exitOpacity?: number;
    enterScale?: number;
    exitScale?: number;
    enterTranslateX?: string;
    exitTranslateX?: string;
    enterTranslateY?: string;
    exitTranslateY?: string;
    enterTiming?: string;
    exitTiming?: string;
    enterDelay?: number;
    exitDelay?: number;
};
export declare const Animated: ({ children, enterAnimations, exitAnimations, enterDuration, exitDuration, enterOpacity, exitOpacity, enterScale, exitScale, enterTranslateX, exitTranslateX, enterTranslateY, exitTranslateY, enterTiming, exitTiming, enterDelay, exitDelay, }: AnimatedProps & {
    children: (dynClass: string | undefined) => ReactElement;
}) => React.JSX.Element;
export declare function splitAnimProps<T extends AnimatedProps>(props: T): [AnimatedProps, Omit<T, keyof AnimatedProps>];
export declare const animPropTypes: ({ defaultEnterAnimations, defaultExitAnimations, }: {
    defaultEnterAnimations?: ((ps: any) => EnterAnim[]) | undefined;
    defaultExitAnimations?: ((ps: any) => ExitAnim[]) | undefined;
}) => CodeComponentMeta<AnimatedProps>["props"];
export declare const overlayStates: {
    readonly open: {
        readonly type: "writable";
        readonly valueProp: "open";
        readonly onChangeProp: "onOpenChange";
        readonly variableType: "boolean";
    };
};
export declare const overlayProps: ({ defaultSlotContent, triggerSlotName, openDisplay, }: {
    defaultSlotContent: any;
    triggerSlotName: string;
    openDisplay?: string | undefined;
}) => CodeComponentMeta<DialogProps>["props"];
export declare function prefixClasses(x: string): string;
export declare function BaseStyles(): React.JSX.Element;
export declare const popoverProps: {
    readonly slideIn: {
        readonly type: "boolean";
        readonly defaultValueHint: true;
        readonly description: "Add additional subtle slide-in animation on reveal, which can depend on where the tooltip is dynamically placed.";
    };
    readonly enterAnimations?: import("@plasmicapp/host").PropType<AnimatedProps> | undefined;
    readonly exitAnimations?: import("@plasmicapp/host").PropType<AnimatedProps> | undefined;
    readonly enterDuration?: "string" | "number" | "boolean" | "object" | "href" | "exprEditor" | "dataPicker" | "imageUrl" | "slot" | import("@plasmicapp/host/prop-types").PlainStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").CodeStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichTextType<AnimatedProps> | import("@plasmicapp/host/prop-types").ColorType<AnimatedProps> | import("@plasmicapp/host/prop-types").ClassType<AnimatedProps> | import("@plasmicapp/host/prop-types").ThemeResetClassType<AnimatedProps> | import("@plasmicapp/host/prop-types").CardPickerType<AnimatedProps> | import("@plasmicapp/host/prop-types").HrefType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichBooleanType<AnimatedProps> | import("@plasmicapp/host/prop-types").GraphQLType<AnimatedProps> | import("@plasmicapp/host/prop-types").PlainNumberType<AnimatedProps> | import("@plasmicapp/host/prop-types").SliderNumberType<AnimatedProps> | import("@plasmicapp/host/prop-types").ObjectType<AnimatedProps> | import("@plasmicapp/host/prop-types").ArrayType<AnimatedProps> | import("@plasmicapp/host/prop-types").DataSourceType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichDataPickerType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichExprEditorType<AnimatedProps> | import("@plasmicapp/host/prop-types").FormValidationRulesType<AnimatedProps> | import("@plasmicapp/host/prop-types").EventHandlerType<AnimatedProps> | import("@plasmicapp/host/prop-types").SingleChoiceType<AnimatedProps, import("@plasmicapp/host").ChoiceValue> | import("@plasmicapp/host/prop-types").MultiChoiceType<AnimatedProps, import("@plasmicapp/host").ChoiceValue> | import("@plasmicapp/host/prop-types").CustomChoiceType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichCustomType<AnimatedProps> | React.ComponentClass<import("@plasmicapp/host").CustomControlProps<AnimatedProps>, any> | React.FunctionComponent<import("@plasmicapp/host").CustomControlProps<AnimatedProps>> | import("@plasmicapp/host/prop-types").DynamicType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichImageUrlType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichSlotType<AnimatedProps> | import("@plasmicapp/host/prop-types").DateStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").DateRangeStringsType<AnimatedProps> | undefined;
    readonly exitDuration?: "string" | "number" | "boolean" | "object" | "href" | "exprEditor" | "dataPicker" | "imageUrl" | "slot" | import("@plasmicapp/host/prop-types").PlainStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").CodeStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichTextType<AnimatedProps> | import("@plasmicapp/host/prop-types").ColorType<AnimatedProps> | import("@plasmicapp/host/prop-types").ClassType<AnimatedProps> | import("@plasmicapp/host/prop-types").ThemeResetClassType<AnimatedProps> | import("@plasmicapp/host/prop-types").CardPickerType<AnimatedProps> | import("@plasmicapp/host/prop-types").HrefType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichBooleanType<AnimatedProps> | import("@plasmicapp/host/prop-types").GraphQLType<AnimatedProps> | import("@plasmicapp/host/prop-types").PlainNumberType<AnimatedProps> | import("@plasmicapp/host/prop-types").SliderNumberType<AnimatedProps> | import("@plasmicapp/host/prop-types").ObjectType<AnimatedProps> | import("@plasmicapp/host/prop-types").ArrayType<AnimatedProps> | import("@plasmicapp/host/prop-types").DataSourceType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichDataPickerType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichExprEditorType<AnimatedProps> | import("@plasmicapp/host/prop-types").FormValidationRulesType<AnimatedProps> | import("@plasmicapp/host/prop-types").EventHandlerType<AnimatedProps> | import("@plasmicapp/host/prop-types").SingleChoiceType<AnimatedProps, import("@plasmicapp/host").ChoiceValue> | import("@plasmicapp/host/prop-types").MultiChoiceType<AnimatedProps, import("@plasmicapp/host").ChoiceValue> | import("@plasmicapp/host/prop-types").CustomChoiceType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichCustomType<AnimatedProps> | React.ComponentClass<import("@plasmicapp/host").CustomControlProps<AnimatedProps>, any> | React.FunctionComponent<import("@plasmicapp/host").CustomControlProps<AnimatedProps>> | import("@plasmicapp/host/prop-types").DynamicType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichImageUrlType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichSlotType<AnimatedProps> | import("@plasmicapp/host/prop-types").DateStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").DateRangeStringsType<AnimatedProps> | undefined;
    readonly enterOpacity?: "string" | "number" | "boolean" | "object" | "href" | "exprEditor" | "dataPicker" | "imageUrl" | "slot" | import("@plasmicapp/host/prop-types").PlainStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").CodeStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichTextType<AnimatedProps> | import("@plasmicapp/host/prop-types").ColorType<AnimatedProps> | import("@plasmicapp/host/prop-types").ClassType<AnimatedProps> | import("@plasmicapp/host/prop-types").ThemeResetClassType<AnimatedProps> | import("@plasmicapp/host/prop-types").CardPickerType<AnimatedProps> | import("@plasmicapp/host/prop-types").HrefType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichBooleanType<AnimatedProps> | import("@plasmicapp/host/prop-types").GraphQLType<AnimatedProps> | import("@plasmicapp/host/prop-types").PlainNumberType<AnimatedProps> | import("@plasmicapp/host/prop-types").SliderNumberType<AnimatedProps> | import("@plasmicapp/host/prop-types").ObjectType<AnimatedProps> | import("@plasmicapp/host/prop-types").ArrayType<AnimatedProps> | import("@plasmicapp/host/prop-types").DataSourceType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichDataPickerType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichExprEditorType<AnimatedProps> | import("@plasmicapp/host/prop-types").FormValidationRulesType<AnimatedProps> | import("@plasmicapp/host/prop-types").EventHandlerType<AnimatedProps> | import("@plasmicapp/host/prop-types").SingleChoiceType<AnimatedProps, import("@plasmicapp/host").ChoiceValue> | import("@plasmicapp/host/prop-types").MultiChoiceType<AnimatedProps, import("@plasmicapp/host").ChoiceValue> | import("@plasmicapp/host/prop-types").CustomChoiceType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichCustomType<AnimatedProps> | React.ComponentClass<import("@plasmicapp/host").CustomControlProps<AnimatedProps>, any> | React.FunctionComponent<import("@plasmicapp/host").CustomControlProps<AnimatedProps>> | import("@plasmicapp/host/prop-types").DynamicType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichImageUrlType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichSlotType<AnimatedProps> | import("@plasmicapp/host/prop-types").DateStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").DateRangeStringsType<AnimatedProps> | undefined;
    readonly exitOpacity?: "string" | "number" | "boolean" | "object" | "href" | "exprEditor" | "dataPicker" | "imageUrl" | "slot" | import("@plasmicapp/host/prop-types").PlainStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").CodeStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichTextType<AnimatedProps> | import("@plasmicapp/host/prop-types").ColorType<AnimatedProps> | import("@plasmicapp/host/prop-types").ClassType<AnimatedProps> | import("@plasmicapp/host/prop-types").ThemeResetClassType<AnimatedProps> | import("@plasmicapp/host/prop-types").CardPickerType<AnimatedProps> | import("@plasmicapp/host/prop-types").HrefType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichBooleanType<AnimatedProps> | import("@plasmicapp/host/prop-types").GraphQLType<AnimatedProps> | import("@plasmicapp/host/prop-types").PlainNumberType<AnimatedProps> | import("@plasmicapp/host/prop-types").SliderNumberType<AnimatedProps> | import("@plasmicapp/host/prop-types").ObjectType<AnimatedProps> | import("@plasmicapp/host/prop-types").ArrayType<AnimatedProps> | import("@plasmicapp/host/prop-types").DataSourceType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichDataPickerType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichExprEditorType<AnimatedProps> | import("@plasmicapp/host/prop-types").FormValidationRulesType<AnimatedProps> | import("@plasmicapp/host/prop-types").EventHandlerType<AnimatedProps> | import("@plasmicapp/host/prop-types").SingleChoiceType<AnimatedProps, import("@plasmicapp/host").ChoiceValue> | import("@plasmicapp/host/prop-types").MultiChoiceType<AnimatedProps, import("@plasmicapp/host").ChoiceValue> | import("@plasmicapp/host/prop-types").CustomChoiceType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichCustomType<AnimatedProps> | React.ComponentClass<import("@plasmicapp/host").CustomControlProps<AnimatedProps>, any> | React.FunctionComponent<import("@plasmicapp/host").CustomControlProps<AnimatedProps>> | import("@plasmicapp/host/prop-types").DynamicType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichImageUrlType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichSlotType<AnimatedProps> | import("@plasmicapp/host/prop-types").DateStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").DateRangeStringsType<AnimatedProps> | undefined;
    readonly enterScale?: "string" | "number" | "boolean" | "object" | "href" | "exprEditor" | "dataPicker" | "imageUrl" | "slot" | import("@plasmicapp/host/prop-types").PlainStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").CodeStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichTextType<AnimatedProps> | import("@plasmicapp/host/prop-types").ColorType<AnimatedProps> | import("@plasmicapp/host/prop-types").ClassType<AnimatedProps> | import("@plasmicapp/host/prop-types").ThemeResetClassType<AnimatedProps> | import("@plasmicapp/host/prop-types").CardPickerType<AnimatedProps> | import("@plasmicapp/host/prop-types").HrefType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichBooleanType<AnimatedProps> | import("@plasmicapp/host/prop-types").GraphQLType<AnimatedProps> | import("@plasmicapp/host/prop-types").PlainNumberType<AnimatedProps> | import("@plasmicapp/host/prop-types").SliderNumberType<AnimatedProps> | import("@plasmicapp/host/prop-types").ObjectType<AnimatedProps> | import("@plasmicapp/host/prop-types").ArrayType<AnimatedProps> | import("@plasmicapp/host/prop-types").DataSourceType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichDataPickerType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichExprEditorType<AnimatedProps> | import("@plasmicapp/host/prop-types").FormValidationRulesType<AnimatedProps> | import("@plasmicapp/host/prop-types").EventHandlerType<AnimatedProps> | import("@plasmicapp/host/prop-types").SingleChoiceType<AnimatedProps, import("@plasmicapp/host").ChoiceValue> | import("@plasmicapp/host/prop-types").MultiChoiceType<AnimatedProps, import("@plasmicapp/host").ChoiceValue> | import("@plasmicapp/host/prop-types").CustomChoiceType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichCustomType<AnimatedProps> | React.ComponentClass<import("@plasmicapp/host").CustomControlProps<AnimatedProps>, any> | React.FunctionComponent<import("@plasmicapp/host").CustomControlProps<AnimatedProps>> | import("@plasmicapp/host/prop-types").DynamicType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichImageUrlType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichSlotType<AnimatedProps> | import("@plasmicapp/host/prop-types").DateStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").DateRangeStringsType<AnimatedProps> | undefined;
    readonly exitScale?: "string" | "number" | "boolean" | "object" | "href" | "exprEditor" | "dataPicker" | "imageUrl" | "slot" | import("@plasmicapp/host/prop-types").PlainStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").CodeStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichTextType<AnimatedProps> | import("@plasmicapp/host/prop-types").ColorType<AnimatedProps> | import("@plasmicapp/host/prop-types").ClassType<AnimatedProps> | import("@plasmicapp/host/prop-types").ThemeResetClassType<AnimatedProps> | import("@plasmicapp/host/prop-types").CardPickerType<AnimatedProps> | import("@plasmicapp/host/prop-types").HrefType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichBooleanType<AnimatedProps> | import("@plasmicapp/host/prop-types").GraphQLType<AnimatedProps> | import("@plasmicapp/host/prop-types").PlainNumberType<AnimatedProps> | import("@plasmicapp/host/prop-types").SliderNumberType<AnimatedProps> | import("@plasmicapp/host/prop-types").ObjectType<AnimatedProps> | import("@plasmicapp/host/prop-types").ArrayType<AnimatedProps> | import("@plasmicapp/host/prop-types").DataSourceType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichDataPickerType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichExprEditorType<AnimatedProps> | import("@plasmicapp/host/prop-types").FormValidationRulesType<AnimatedProps> | import("@plasmicapp/host/prop-types").EventHandlerType<AnimatedProps> | import("@plasmicapp/host/prop-types").SingleChoiceType<AnimatedProps, import("@plasmicapp/host").ChoiceValue> | import("@plasmicapp/host/prop-types").MultiChoiceType<AnimatedProps, import("@plasmicapp/host").ChoiceValue> | import("@plasmicapp/host/prop-types").CustomChoiceType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichCustomType<AnimatedProps> | React.ComponentClass<import("@plasmicapp/host").CustomControlProps<AnimatedProps>, any> | React.FunctionComponent<import("@plasmicapp/host").CustomControlProps<AnimatedProps>> | import("@plasmicapp/host/prop-types").DynamicType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichImageUrlType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichSlotType<AnimatedProps> | import("@plasmicapp/host/prop-types").DateStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").DateRangeStringsType<AnimatedProps> | undefined;
    readonly enterTranslateX?: "string" | "number" | "boolean" | "object" | "href" | "exprEditor" | "dataPicker" | "imageUrl" | "slot" | import("@plasmicapp/host/prop-types").PlainStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").CodeStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichTextType<AnimatedProps> | import("@plasmicapp/host/prop-types").ColorType<AnimatedProps> | import("@plasmicapp/host/prop-types").ClassType<AnimatedProps> | import("@plasmicapp/host/prop-types").ThemeResetClassType<AnimatedProps> | import("@plasmicapp/host/prop-types").CardPickerType<AnimatedProps> | import("@plasmicapp/host/prop-types").HrefType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichBooleanType<AnimatedProps> | import("@plasmicapp/host/prop-types").GraphQLType<AnimatedProps> | import("@plasmicapp/host/prop-types").PlainNumberType<AnimatedProps> | import("@plasmicapp/host/prop-types").SliderNumberType<AnimatedProps> | import("@plasmicapp/host/prop-types").ObjectType<AnimatedProps> | import("@plasmicapp/host/prop-types").ArrayType<AnimatedProps> | import("@plasmicapp/host/prop-types").DataSourceType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichDataPickerType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichExprEditorType<AnimatedProps> | import("@plasmicapp/host/prop-types").FormValidationRulesType<AnimatedProps> | import("@plasmicapp/host/prop-types").EventHandlerType<AnimatedProps> | import("@plasmicapp/host/prop-types").SingleChoiceType<AnimatedProps, import("@plasmicapp/host").ChoiceValue> | import("@plasmicapp/host/prop-types").MultiChoiceType<AnimatedProps, import("@plasmicapp/host").ChoiceValue> | import("@plasmicapp/host/prop-types").CustomChoiceType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichCustomType<AnimatedProps> | React.ComponentClass<import("@plasmicapp/host").CustomControlProps<AnimatedProps>, any> | React.FunctionComponent<import("@plasmicapp/host").CustomControlProps<AnimatedProps>> | import("@plasmicapp/host/prop-types").DynamicType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichImageUrlType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichSlotType<AnimatedProps> | import("@plasmicapp/host/prop-types").DateStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").DateRangeStringsType<AnimatedProps> | undefined;
    readonly exitTranslateX?: "string" | "number" | "boolean" | "object" | "href" | "exprEditor" | "dataPicker" | "imageUrl" | "slot" | import("@plasmicapp/host/prop-types").PlainStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").CodeStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichTextType<AnimatedProps> | import("@plasmicapp/host/prop-types").ColorType<AnimatedProps> | import("@plasmicapp/host/prop-types").ClassType<AnimatedProps> | import("@plasmicapp/host/prop-types").ThemeResetClassType<AnimatedProps> | import("@plasmicapp/host/prop-types").CardPickerType<AnimatedProps> | import("@plasmicapp/host/prop-types").HrefType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichBooleanType<AnimatedProps> | import("@plasmicapp/host/prop-types").GraphQLType<AnimatedProps> | import("@plasmicapp/host/prop-types").PlainNumberType<AnimatedProps> | import("@plasmicapp/host/prop-types").SliderNumberType<AnimatedProps> | import("@plasmicapp/host/prop-types").ObjectType<AnimatedProps> | import("@plasmicapp/host/prop-types").ArrayType<AnimatedProps> | import("@plasmicapp/host/prop-types").DataSourceType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichDataPickerType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichExprEditorType<AnimatedProps> | import("@plasmicapp/host/prop-types").FormValidationRulesType<AnimatedProps> | import("@plasmicapp/host/prop-types").EventHandlerType<AnimatedProps> | import("@plasmicapp/host/prop-types").SingleChoiceType<AnimatedProps, import("@plasmicapp/host").ChoiceValue> | import("@plasmicapp/host/prop-types").MultiChoiceType<AnimatedProps, import("@plasmicapp/host").ChoiceValue> | import("@plasmicapp/host/prop-types").CustomChoiceType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichCustomType<AnimatedProps> | React.ComponentClass<import("@plasmicapp/host").CustomControlProps<AnimatedProps>, any> | React.FunctionComponent<import("@plasmicapp/host").CustomControlProps<AnimatedProps>> | import("@plasmicapp/host/prop-types").DynamicType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichImageUrlType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichSlotType<AnimatedProps> | import("@plasmicapp/host/prop-types").DateStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").DateRangeStringsType<AnimatedProps> | undefined;
    readonly enterTranslateY?: "string" | "number" | "boolean" | "object" | "href" | "exprEditor" | "dataPicker" | "imageUrl" | "slot" | import("@plasmicapp/host/prop-types").PlainStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").CodeStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichTextType<AnimatedProps> | import("@plasmicapp/host/prop-types").ColorType<AnimatedProps> | import("@plasmicapp/host/prop-types").ClassType<AnimatedProps> | import("@plasmicapp/host/prop-types").ThemeResetClassType<AnimatedProps> | import("@plasmicapp/host/prop-types").CardPickerType<AnimatedProps> | import("@plasmicapp/host/prop-types").HrefType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichBooleanType<AnimatedProps> | import("@plasmicapp/host/prop-types").GraphQLType<AnimatedProps> | import("@plasmicapp/host/prop-types").PlainNumberType<AnimatedProps> | import("@plasmicapp/host/prop-types").SliderNumberType<AnimatedProps> | import("@plasmicapp/host/prop-types").ObjectType<AnimatedProps> | import("@plasmicapp/host/prop-types").ArrayType<AnimatedProps> | import("@plasmicapp/host/prop-types").DataSourceType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichDataPickerType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichExprEditorType<AnimatedProps> | import("@plasmicapp/host/prop-types").FormValidationRulesType<AnimatedProps> | import("@plasmicapp/host/prop-types").EventHandlerType<AnimatedProps> | import("@plasmicapp/host/prop-types").SingleChoiceType<AnimatedProps, import("@plasmicapp/host").ChoiceValue> | import("@plasmicapp/host/prop-types").MultiChoiceType<AnimatedProps, import("@plasmicapp/host").ChoiceValue> | import("@plasmicapp/host/prop-types").CustomChoiceType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichCustomType<AnimatedProps> | React.ComponentClass<import("@plasmicapp/host").CustomControlProps<AnimatedProps>, any> | React.FunctionComponent<import("@plasmicapp/host").CustomControlProps<AnimatedProps>> | import("@plasmicapp/host/prop-types").DynamicType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichImageUrlType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichSlotType<AnimatedProps> | import("@plasmicapp/host/prop-types").DateStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").DateRangeStringsType<AnimatedProps> | undefined;
    readonly exitTranslateY?: "string" | "number" | "boolean" | "object" | "href" | "exprEditor" | "dataPicker" | "imageUrl" | "slot" | import("@plasmicapp/host/prop-types").PlainStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").CodeStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichTextType<AnimatedProps> | import("@plasmicapp/host/prop-types").ColorType<AnimatedProps> | import("@plasmicapp/host/prop-types").ClassType<AnimatedProps> | import("@plasmicapp/host/prop-types").ThemeResetClassType<AnimatedProps> | import("@plasmicapp/host/prop-types").CardPickerType<AnimatedProps> | import("@plasmicapp/host/prop-types").HrefType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichBooleanType<AnimatedProps> | import("@plasmicapp/host/prop-types").GraphQLType<AnimatedProps> | import("@plasmicapp/host/prop-types").PlainNumberType<AnimatedProps> | import("@plasmicapp/host/prop-types").SliderNumberType<AnimatedProps> | import("@plasmicapp/host/prop-types").ObjectType<AnimatedProps> | import("@plasmicapp/host/prop-types").ArrayType<AnimatedProps> | import("@plasmicapp/host/prop-types").DataSourceType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichDataPickerType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichExprEditorType<AnimatedProps> | import("@plasmicapp/host/prop-types").FormValidationRulesType<AnimatedProps> | import("@plasmicapp/host/prop-types").EventHandlerType<AnimatedProps> | import("@plasmicapp/host/prop-types").SingleChoiceType<AnimatedProps, import("@plasmicapp/host").ChoiceValue> | import("@plasmicapp/host/prop-types").MultiChoiceType<AnimatedProps, import("@plasmicapp/host").ChoiceValue> | import("@plasmicapp/host/prop-types").CustomChoiceType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichCustomType<AnimatedProps> | React.ComponentClass<import("@plasmicapp/host").CustomControlProps<AnimatedProps>, any> | React.FunctionComponent<import("@plasmicapp/host").CustomControlProps<AnimatedProps>> | import("@plasmicapp/host/prop-types").DynamicType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichImageUrlType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichSlotType<AnimatedProps> | import("@plasmicapp/host/prop-types").DateStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").DateRangeStringsType<AnimatedProps> | undefined;
    readonly enterTiming?: "string" | "number" | "boolean" | "object" | "href" | "exprEditor" | "dataPicker" | "imageUrl" | "slot" | import("@plasmicapp/host/prop-types").PlainStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").CodeStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichTextType<AnimatedProps> | import("@plasmicapp/host/prop-types").ColorType<AnimatedProps> | import("@plasmicapp/host/prop-types").ClassType<AnimatedProps> | import("@plasmicapp/host/prop-types").ThemeResetClassType<AnimatedProps> | import("@plasmicapp/host/prop-types").CardPickerType<AnimatedProps> | import("@plasmicapp/host/prop-types").HrefType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichBooleanType<AnimatedProps> | import("@plasmicapp/host/prop-types").GraphQLType<AnimatedProps> | import("@plasmicapp/host/prop-types").PlainNumberType<AnimatedProps> | import("@plasmicapp/host/prop-types").SliderNumberType<AnimatedProps> | import("@plasmicapp/host/prop-types").ObjectType<AnimatedProps> | import("@plasmicapp/host/prop-types").ArrayType<AnimatedProps> | import("@plasmicapp/host/prop-types").DataSourceType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichDataPickerType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichExprEditorType<AnimatedProps> | import("@plasmicapp/host/prop-types").FormValidationRulesType<AnimatedProps> | import("@plasmicapp/host/prop-types").EventHandlerType<AnimatedProps> | import("@plasmicapp/host/prop-types").SingleChoiceType<AnimatedProps, import("@plasmicapp/host").ChoiceValue> | import("@plasmicapp/host/prop-types").MultiChoiceType<AnimatedProps, import("@plasmicapp/host").ChoiceValue> | import("@plasmicapp/host/prop-types").CustomChoiceType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichCustomType<AnimatedProps> | React.ComponentClass<import("@plasmicapp/host").CustomControlProps<AnimatedProps>, any> | React.FunctionComponent<import("@plasmicapp/host").CustomControlProps<AnimatedProps>> | import("@plasmicapp/host/prop-types").DynamicType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichImageUrlType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichSlotType<AnimatedProps> | import("@plasmicapp/host/prop-types").DateStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").DateRangeStringsType<AnimatedProps> | undefined;
    readonly exitTiming?: "string" | "number" | "boolean" | "object" | "href" | "exprEditor" | "dataPicker" | "imageUrl" | "slot" | import("@plasmicapp/host/prop-types").PlainStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").CodeStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichTextType<AnimatedProps> | import("@plasmicapp/host/prop-types").ColorType<AnimatedProps> | import("@plasmicapp/host/prop-types").ClassType<AnimatedProps> | import("@plasmicapp/host/prop-types").ThemeResetClassType<AnimatedProps> | import("@plasmicapp/host/prop-types").CardPickerType<AnimatedProps> | import("@plasmicapp/host/prop-types").HrefType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichBooleanType<AnimatedProps> | import("@plasmicapp/host/prop-types").GraphQLType<AnimatedProps> | import("@plasmicapp/host/prop-types").PlainNumberType<AnimatedProps> | import("@plasmicapp/host/prop-types").SliderNumberType<AnimatedProps> | import("@plasmicapp/host/prop-types").ObjectType<AnimatedProps> | import("@plasmicapp/host/prop-types").ArrayType<AnimatedProps> | import("@plasmicapp/host/prop-types").DataSourceType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichDataPickerType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichExprEditorType<AnimatedProps> | import("@plasmicapp/host/prop-types").FormValidationRulesType<AnimatedProps> | import("@plasmicapp/host/prop-types").EventHandlerType<AnimatedProps> | import("@plasmicapp/host/prop-types").SingleChoiceType<AnimatedProps, import("@plasmicapp/host").ChoiceValue> | import("@plasmicapp/host/prop-types").MultiChoiceType<AnimatedProps, import("@plasmicapp/host").ChoiceValue> | import("@plasmicapp/host/prop-types").CustomChoiceType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichCustomType<AnimatedProps> | React.ComponentClass<import("@plasmicapp/host").CustomControlProps<AnimatedProps>, any> | React.FunctionComponent<import("@plasmicapp/host").CustomControlProps<AnimatedProps>> | import("@plasmicapp/host/prop-types").DynamicType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichImageUrlType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichSlotType<AnimatedProps> | import("@plasmicapp/host/prop-types").DateStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").DateRangeStringsType<AnimatedProps> | undefined;
    readonly enterDelay?: "string" | "number" | "boolean" | "object" | "href" | "exprEditor" | "dataPicker" | "imageUrl" | "slot" | import("@plasmicapp/host/prop-types").PlainStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").CodeStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichTextType<AnimatedProps> | import("@plasmicapp/host/prop-types").ColorType<AnimatedProps> | import("@plasmicapp/host/prop-types").ClassType<AnimatedProps> | import("@plasmicapp/host/prop-types").ThemeResetClassType<AnimatedProps> | import("@plasmicapp/host/prop-types").CardPickerType<AnimatedProps> | import("@plasmicapp/host/prop-types").HrefType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichBooleanType<AnimatedProps> | import("@plasmicapp/host/prop-types").GraphQLType<AnimatedProps> | import("@plasmicapp/host/prop-types").PlainNumberType<AnimatedProps> | import("@plasmicapp/host/prop-types").SliderNumberType<AnimatedProps> | import("@plasmicapp/host/prop-types").ObjectType<AnimatedProps> | import("@plasmicapp/host/prop-types").ArrayType<AnimatedProps> | import("@plasmicapp/host/prop-types").DataSourceType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichDataPickerType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichExprEditorType<AnimatedProps> | import("@plasmicapp/host/prop-types").FormValidationRulesType<AnimatedProps> | import("@plasmicapp/host/prop-types").EventHandlerType<AnimatedProps> | import("@plasmicapp/host/prop-types").SingleChoiceType<AnimatedProps, import("@plasmicapp/host").ChoiceValue> | import("@plasmicapp/host/prop-types").MultiChoiceType<AnimatedProps, import("@plasmicapp/host").ChoiceValue> | import("@plasmicapp/host/prop-types").CustomChoiceType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichCustomType<AnimatedProps> | React.ComponentClass<import("@plasmicapp/host").CustomControlProps<AnimatedProps>, any> | React.FunctionComponent<import("@plasmicapp/host").CustomControlProps<AnimatedProps>> | import("@plasmicapp/host/prop-types").DynamicType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichImageUrlType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichSlotType<AnimatedProps> | import("@plasmicapp/host/prop-types").DateStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").DateRangeStringsType<AnimatedProps> | undefined;
    readonly exitDelay?: "string" | "number" | "boolean" | "object" | "href" | "exprEditor" | "dataPicker" | "imageUrl" | "slot" | import("@plasmicapp/host/prop-types").PlainStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").CodeStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichTextType<AnimatedProps> | import("@plasmicapp/host/prop-types").ColorType<AnimatedProps> | import("@plasmicapp/host/prop-types").ClassType<AnimatedProps> | import("@plasmicapp/host/prop-types").ThemeResetClassType<AnimatedProps> | import("@plasmicapp/host/prop-types").CardPickerType<AnimatedProps> | import("@plasmicapp/host/prop-types").HrefType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichBooleanType<AnimatedProps> | import("@plasmicapp/host/prop-types").GraphQLType<AnimatedProps> | import("@plasmicapp/host/prop-types").PlainNumberType<AnimatedProps> | import("@plasmicapp/host/prop-types").SliderNumberType<AnimatedProps> | import("@plasmicapp/host/prop-types").ObjectType<AnimatedProps> | import("@plasmicapp/host/prop-types").ArrayType<AnimatedProps> | import("@plasmicapp/host/prop-types").DataSourceType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichDataPickerType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichExprEditorType<AnimatedProps> | import("@plasmicapp/host/prop-types").FormValidationRulesType<AnimatedProps> | import("@plasmicapp/host/prop-types").EventHandlerType<AnimatedProps> | import("@plasmicapp/host/prop-types").SingleChoiceType<AnimatedProps, import("@plasmicapp/host").ChoiceValue> | import("@plasmicapp/host/prop-types").MultiChoiceType<AnimatedProps, import("@plasmicapp/host").ChoiceValue> | import("@plasmicapp/host/prop-types").CustomChoiceType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichCustomType<AnimatedProps> | React.ComponentClass<import("@plasmicapp/host").CustomControlProps<AnimatedProps>, any> | React.FunctionComponent<import("@plasmicapp/host").CustomControlProps<AnimatedProps>> | import("@plasmicapp/host/prop-types").DynamicType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichImageUrlType<AnimatedProps> | import("@plasmicapp/host/prop-types").RichSlotType<AnimatedProps> | import("@plasmicapp/host/prop-types").DateStringType<AnimatedProps> | import("@plasmicapp/host/prop-types").DateRangeStringsType<AnimatedProps> | undefined;
    readonly side: {
        readonly type: "choice";
        readonly options: string[];
        readonly defaultValueHint: "bottom";
    };
    readonly sideOffset: {
        readonly type: "number";
        readonly defaultValueHint: 0;
        readonly advanced: true;
    };
    readonly align: {
        readonly type: "choice";
        readonly options: string[];
        readonly defaultValueHint: "center";
    };
    readonly alignOffset: {
        readonly type: "number";
        readonly defaultValueHint: 0;
        readonly advanced: true;
    };
};
export type PopoverExtraProps = AnimatedProps & {
    themeResetClass?: string;
    overlay?: ReactNode;
    slideIn?: boolean;
};
export declare function wrapFragmentInDiv(node: React.ReactNode, className?: string): React.ReactNode;
